#!/bin/bash
# Ink Chamber keyframe chain K02..K11 (stills-only). Each references the PREVIOUS accepted
# keyframe so the dark look + blade direction + product identity stay continuous.
WORK="/Users/jang/Products/ease-design/specs/021-scrollworld-gflow-video-track"
cd "$WORK/product-slice"
CX(){ CMUX_CODEX_HOOKS_DISABLED=1 codex exec -C "$WORK" -s workspace-write --skip-git-repo-check "$@" </dev/null; }
FROZEN='Use the image generation tool ($imagegen) with the attached image as the reference. Keep the EXACT same dark cinematic look as the reference: INK-black vertical gradient background with a soft charcoal pool, the product FLOATING with no floor (only a soft dark contact-occlusion pool beneath), the BLADE rim light from back-left and slightly high drawing continuous cold near-white lines on the headband arc and earcup/metal edges, the dim overhead POOL key, deeply crushed blacks at roughly 8:1 contrast, 85mm telephoto compression, premium cinematic product film, realistic materials (brushed-metal anisotropy, leather grain). Keep the background, the lighting DIRECTION and the product identity identical to the reference. No text, no logo, no props. Wide 16:9.'

gen(){ # $1=out KNN  $2=ref  $3=delta
  echo "== $1 (ref $2) =="
  CX "$FROZEN The ONLY changes from the reference: $3 Save it as ./product-slice/refs/$1.png. Do not do anything else." -i "$WORK/product-slice/refs/$2.png" > "refs/gen-$1.out" 2>&1
  [ -f "refs/$1.png" ] && echo "$1 OK $(stat -f%z refs/$1.png)" || { echo "$1 FAIL"; tail -2 "refs/gen-$1.out"; }
}

gen K02 K01 'the camera has orbited about 25 degrees toward a three-quarter-front view and risen to earcup level, pushed in slightly so the product fills about 48 percent of frame height. The POOL key now blooms to full so the leather grain and the brushed-metal streak read clearly; contrast settles at about 8:1. The soft occlusion pool appears beneath. Product whole and assembled, right of center; keep a black void in the lower-left third.'
gen K03 K02 'the camera continues orbiting about 15 degrees and moves medium-close on the FRONT (left) earcup so that cup fills about 45 percent of frame height, slightly right of center. The background pool sits directly behind the cup to halo-separate it. The earcup shell is fully opaque and perfect. Keep the left third as an empty black void. Product still fully assembled.'
gen K04 K03 'a small push closer, a few degrees higher looking down into the front earcup (cup about 60 percent of frame height). The outer shell cap of that earcup is now SMOKED GLASS — through it you can see the internals (grille, 40mm driver, circuit board) but they are UNLIT and cold, only lit by the blade sliver on the glass. Everything else identical and assembled. A held, quiet breath.'
gen K05 K04 'IDENTICAL camera and framing to the reference (do not move the camera). The EMBER now IGNITES inside the transparent shell: the copper voice coil and the PCB traces glow warm orange (#ff3e00-shifted), becoming the brightest thing in the frame; the exterior of the product drops about one stop darker; the glass shell picks up an interior warm bounce plus the cold blade sliver. This is the revelation. Keep a black void on the right side.'
gen K06 K05 'the camera pulls back and RISES toward a high three-quarter (about 12 degrees above). The warm ember stays lit. The front earcup has just BEGUN to explode: only the leather cushion and the fabric ring have peeled outward from the cup along a lower-left to upper-right diagonal with unequal gaps; the rest of the parts are still seated. Mid-gesture, not fully exploded, not posed. Faint ember warmth touches the departing cushion.'
gen K07 K06 'the camera is now at a high three-quarter angle, about 20 degrees above. The FRONT earcup is FULLY exploded into its parts suspended along a clean lower-left to upper-right diagonal into depth, each successive part smaller (Z-recession): leather cushion, fabric ring, grille, damping ring, circular PCB, and the 40mm driver+copper-coil cluster crowned as the brightest jewel lit by the ember at maximum, then the shell cap furthest out turned about 15 degrees toward camera. The headband and the far earcup and yokes levitate above, arc intact, fully assembled. The blade rim carves every part edge. Foreground cushion edge softly defocused. Dark voids between clusters for callouts.'
gen K08 K07 'the same fully-exploded constellation as the reference, but the camera has drifted laterally about 8 percent and orbited about 10 degrees — a parallax shift proving depth. Lighting and ember identical. Composition still leaves dark voids readable.'
gen K09 K08 'the camera descends and orbits back toward three-quarter-front (product about 50 percent width). The parts are mid-flight HOMEWARD, in a tighter cluster than fully exploded — the driver and inner parts have re-seated, the ember is DIMMING and half-swallowed. The shell cap is still out with its 15-degree face turn. Reassembly in progress.'
gen K10 K09 'the camera is at earcup-level three-quarter-front (a tighter echo of the assembled look). The earcup is fully SEALED and reassembled, the ember is GONE — only the cold blade rim and dim pool remain. The product is whole again, poised and still.'
gen K11 K10 'the camera returns to a LOW near-profile (an echo of the opening monument, slightly closer). Only the blade rim and a low pool light it — the deepest, darkest frame of the film. The product is whole and floating. Keep a large black void in the lower-left third for the wordmark.'
echo "INK CHAIN DONE: $(ls refs/K0*.png refs/K1*.png 2>/dev/null | wc -l | tr -d ' ')/11"
