/**
 * Phase 05's paired test: the `tell` family.
 *
 * The catalog rows were GENERATED by a regex over the rule modules. If this test
 * verified them with the same regex it would be green by construction and blind
 * to whatever the regex cannot see — a tautology that already cost this repo six
 * missing checks and two wrong severities. So the pairing here is against
 * RUNTIME state: the imported roster and what the linter actually emits.
 *
 * Two further contracts:
 *  - rules import nothing from an extractor, or the family is web-only again;
 *  - every rule can fire AND stay silent, proven per rule, not sampled.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { TELL_RULES, TELL_REQUIREMENTS, lintTell, tellCoverage } from "../src/core/tell-lint.js";
import { CHECK_CATALOG } from "../src/core/check-catalog.js";
import { RENDERED_RULES } from "../src/core/tell-rules-rendered.js";
import { GATE_FAMILIES } from "../src/core/gate.js";
import { EXTRACTOR_PROFILES, extractorById } from "../src/core/design-facts/index.js";
import type { DesignFact, Provenance } from "../src/core/design-facts/index.js";

const CORE = join(fileURLToPath(new URL("..", import.meta.url)), "src", "core");

const html = extractorById("html-cascade")!;
const swift = extractorById("swiftui")!;

const at = (line = 1): Provenance => ({ file: "f", line, extractor: "html-cascade", confidence: "resolved" });

describe("family registration", () => {
  it("is a gate family", () => {
    expect(GATE_FAMILIES).toContain("tell");
  });

  it("pairs the catalog against the RUNTIME roster, not against its own generator", () => {
    // The family has two rosters with different shapes: 36 rules over facts and
    // 7 over a settled render. Pairing against only the first would let a
    // rendered row rot unnoticed — the catalog must account for both.
    const fromRuntime = new Set([...TELL_RULES, ...RENDERED_RULES].map((r) => r.id));
    const fromCatalog = new Set(CHECK_CATALOG.filter((e) => e.family === "tell").map((e) => e.id));
    expect([...fromRuntime].sort()).toEqual([...fromCatalog].sort());
    expect(TELL_RULES).toHaveLength(36);
    expect(RENDERED_RULES).toHaveLength(7);
  });

  it("declares in the catalog exactly the fact kinds each rule declares at runtime", () => {
    for (const rule of TELL_RULES) {
      const row = CHECK_CATALOG.find((e) => e.id === rule.id && e.family === "tell");
      expect(row, rule.id).toBeDefined();
      const requires = row?.requires;
      expect(typeof requires, rule.id).toBe("object");
      if (typeof requires === "object") {
        expect([...requires.facts].sort(), rule.id).toEqual([...rule.needs].sort());
      }
    }
  });

  it("has no duplicate ids and every id is kebab-case", () => {
    const ids = TELL_RULES.map((r) => r.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z][a-z0-9-]*$/);
  });

  it("cites a section that exists in knowledge/design-tells.md", () => {
    const doc = readFileSync(join(CORE, "..", "..", "knowledge", "design-tells.md"), "utf8");
    for (const rule of TELL_RULES) {
      expect(doc, rule.id).toContain(`## ${rule.section}`);
      // The standard must actually describe the rule it claims to emit.
      expect(doc, rule.id).toContain(`**${rule.id}**`);
    }
    // The rendered rules carry no `section` field, but the standard still owes
    // each one a description — a rule the knowledge never mentions is a rule
    // nobody agreed to.
    expect(doc).toContain("## Rendered");
    for (const rule of RENDERED_RULES) expect(doc, rule.id).toContain(`**${rule.id}**`);
  });

  it("defaults to advisory — a tell prints, it does not fail a build", () => {
    const errors = TELL_RULES.filter((r) => r.severity === "error").map((r) => r.id);
    expect(errors.sort()).toEqual(["gradient-text", "justified-text", "side-tab"]);
    expect(TELL_RULES.every((r) => r.severity === "error" || r.severity === "advisory")).toBe(true);
  });
});

describe("architecture boundary", () => {
  it("rules import nothing from an extractor", () => {
    const ruleFiles = readdirSync(CORE).filter((f) => /^tell-rules(-\w+)?\.ts$/.test(f));
    expect(ruleFiles.length).toBeGreaterThanOrEqual(5);
    for (const f of ruleFiles) {
      const src = readFileSync(join(CORE, f), "utf8");
      // Strip comments first: a docblock mentioning extractors must not fail
      // this, and matching prose instead of code is a real way to fake a guard.
      const code = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
      expect(code, f).not.toMatch(/from\s+"\.\/extractors\//);
      expect(code, f).not.toMatch(/htmlparser2|css-tree|css-select/);
    }
  });
});

describe("NOT-EVALUATED, never a silent pass", () => {
  it("reports structure-dependent rules as not-evaluated on a literal-tier extractor", () => {
    const r = lintTell([], swift);
    const ids = r.notEvaluated.map((n) => n.id);
    // swiftui supplies no `structure`, so every rule needing it must be here.
    expect(ids).toContain("nested-cards");
    expect(ids).toContain("monotonous-spacing");
    expect(ids).toContain("icon-tile-stack");
    for (const n of r.notEvaluated) expect(n.reason).toContain("missing");
  });

  it("runs every rule on the reference extractor", () => {
    expect(lintTell([], html).notEvaluated).toEqual([]);
  });

  it("builds a rule x extractor matrix over every registered extractor", () => {
    // All 43: the 36 fact rules AND the 7 rendered ones. Listing only the first
    // set would leave the rendered rules invisible, and a rule nobody can see is
    // a rule nobody notices has stopped running.
    const matrix = tellCoverage(EXTRACTOR_PROFILES);
    expect(matrix).toHaveLength(43);
    for (const row of matrix) expect(row.byExtractor).toHaveLength(EXTRACTOR_PROFILES.length);
    // The rendered rules run against exactly one extractor, and are
    // NOT-EVALUATED against every other.
    const hidden = matrix.find((r) => r.id === "content-hidden-at-rest");
    const runsOn = hidden?.byExtractor.filter((b) => b.runnable).map((b) => b.extractor);
    expect(runsOn).toEqual(["rendered-cdp"]);
  });
});

/**
 * Per-rule firing evidence. Each entry hands the family the minimum facts that
 * SHOULD trip exactly that rule. Sampling a few would certify the rest untested,
 * so the table is required to cover the whole roster and a missing entry fails.
 */
const FIRES: Record<string, DesignFact[]> = {
  "side-tab": [
    { kind: "border", sides: ["left"], widthPx: 4, at: at(3) },
    { kind: "radius", px: 16, at: at(3) },
  ],
  "border-accent-on-rounded": [
    { kind: "border", sides: ["top", "right", "bottom", "left"], widthPx: 4, at: at(4) },
    { kind: "radius", px: 16, at: at(4) },
  ],
  "nested-cards": [
    { kind: "structure", node: "div", depth: 1, ref: "outer", roles: ["card"], at: at(5) },
    { kind: "structure", node: "div", depth: 2, ref: "inner", parentRef: "outer", roles: ["card"], at: at(6) },
  ],
  "monotonous-spacing": Array.from({ length: 8 }, (_, i): DesignFact => ({
    kind: "spacing", prop: "padding-top", px: 16, at: at(10 + i),
  })).concat([{ kind: "structure", node: "div", depth: 0, ref: "r", at: at(9) }]),
  "cramped-padding": [
    { kind: "spacing", prop: "padding-top", px: 4, at: at(7) },
    { kind: "radius", px: 16, at: at(7) },
  ],
  "edge-flush-cards": [
    { kind: "structure", node: "div", depth: 1, ref: "a", roles: ["card"], at: at(8) },
    { kind: "structure", node: "div", depth: 1, ref: "b", roles: ["card"], at: at(9) },
    { kind: "spacing", prop: "padding-top", px: 16, at: at(8) },
    { kind: "radius", px: 8, at: at(8) },
  ],
  "repeated-container-text": Array.from({ length: 3 }, (_, i): DesignFact => ({
    kind: "text", content: "Everything you need to ship faster than before", role: "body", at: at(20 + i),
  })).concat([{ kind: "structure", node: "div", depth: 0, ref: "r", at: at(19) }]),
  "icon-tile-stack": Array.from({ length: 3 }, (_, i): DesignFact[] => [
    { kind: "structure", node: "div", depth: 2, ref: `i${i}`, roles: ["icon"], at: at(30 + i) },
    { kind: "radius", px: 12, at: at(30 + i) },
  ]).flat(),
  "kicker-above-heading": Array.from({ length: 3 }, (_, i): DesignFact[] => [
    { kind: "text", content: "WHY IT MATTERS", role: "body", at: at(40 + i) },
    { kind: "typography", transform: "uppercase", sizePx: 12, at: at(40 + i) },
  ]).flat(),
  "hero-eyebrow-chip": [
    { kind: "text", content: "New", role: "body", at: at(50) },
    { kind: "radius", px: 999, at: at(50) },
    { kind: "typography", sizePx: 12, at: at(50) },
    { kind: "text", content: "Ship design systems", role: "heading", level: 1, at: at(52) },
  ],
  "numbered-section-labels": ["01", "02", "03"].map((n, i): DesignFact => ({
    kind: "text", content: n, role: "body", at: at(60 + i),
  })),
  "ai-color-palette": [{ kind: "color", hex: "7c3aed", role: "bg", at: at(70) }],
  "cream-palette": [{ kind: "color", hex: "faf7f0", role: "bg", at: at(71) }],
  "gradient-text": [
    { kind: "color", hex: "000000", alpha: 0, role: "fg", at: at(72) },
    { kind: "gradient", gradientKind: "linear", stops: [{ hex: "a855f7" }, { hex: "3b82f6" }], at: at(72) },
  ],
  "dark-glow": [
    { kind: "color", hex: "0a0a12", role: "bg", at: at(73) },
    { kind: "shadow", offsetXPx: 0, offsetYPx: 0, blurPx: 40, hex: "7c3aed", at: at(74) },
  ],
  "radial-halo": [{ kind: "gradient", gradientKind: "radial", stops: [{ hex: "222222" }], at: at(75) }],
  "repeating-stripes-gradient": [{
    kind: "gradient", gradientKind: "linear",
    stops: [{ hex: "eeeeee" }, { hex: "ffffff" }, { hex: "eeeeee" }, { hex: "ffffff" }], at: at(76),
  }],
  "gray-on-color": [
    { kind: "color", hex: "9ca3af", role: "fg", at: at(77) },
    { kind: "color", hex: "7c3aed", role: "bg", at: at(77) },
  ],
  "gpt-thin-border-wide-shadow": [
    { kind: "border", sides: ["top", "right", "bottom", "left"], widthPx: 1, at: at(78) },
    { kind: "shadow", offsetXPx: 0, offsetYPx: 4, blurPx: 24, at: at(78) },
  ],
  "codex-grid-background": [
    { kind: "gradient", gradientKind: "linear", angleDeg: 90, stops: [{ hex: "f4f4f4" }, { hex: "fafafa" }], at: at(79) },
    { kind: "gradient", gradientKind: "linear", angleDeg: 0, stops: [{ hex: "f4f4f4" }, { hex: "fafafa" }], at: at(80) },
    { kind: "color", hex: "ffffff", role: "bg", at: at(79) },
  ],
  "overused-font": [{ kind: "typography", family: "Inter", at: at(81) }],
  // A display size must be present: a fragment whose sizes are all UI chrome has
  // no hierarchy to be flat. 28/30/32 is a display scale with no step.
  "flat-type-hierarchy": [28, 30, 32].map((n, i): DesignFact => ({ kind: "typography", sizePx: n, at: at(82 + i) })),
  "oversized-h1": [
    { kind: "text", content: "Big", role: "heading", level: 1, at: at(90) },
    { kind: "typography", sizePx: 96, at: at(90) },
    { kind: "typography", sizePx: 16, at: at(91) },
  ],
  "heading-rhythm": [
    { kind: "text", content: "a", role: "heading", level: 1, at: at(92) },
    { kind: "typography", sizePx: 24, at: at(92) },
    { kind: "text", content: "b", role: "heading", level: 2, at: at(93) },
    { kind: "typography", sizePx: 40, at: at(93) },
  ],
  "tight-leading": [{ kind: "typography", sizePx: 16, lineHeight: 1.05, at: at(94) }],
  "wide-tracking": [{ kind: "typography", letterSpacingEm: 0.3, at: at(95) }],
  "extreme-negative-tracking": [{ kind: "typography", letterSpacingEm: -0.09, at: at(96) }],
  "line-length": [
    { kind: "text", content: "x".repeat(500), role: "body", at: at(97) },
    { kind: "typography", sizePx: 16, at: at(97) },
  ],
  "justified-text": [{ kind: "typography", align: "justify", at: at(98) }],
  "undersized-ui-text": [
    { kind: "text", content: "Save", role: "label", at: at(99) },
    { kind: "typography", sizePx: 10, at: at(99) },
  ],
  "pulsing-dot": [
    { kind: "motion", motionKind: "animation", repeatsForever: true, durationMs: 2000, at: at(100) },
    { kind: "radius", px: 999, at: at(100) },
  ],
  "blinking-cursor": [
    { kind: "motion", motionKind: "animation", repeatsForever: true, durationMs: 900, at: at(101) },
    { kind: "structure", node: "div", depth: 0, ref: "r", at: at(101) },
  ],
  marquee: [{ kind: "motion", motionKind: "animation", repeatsForever: true, durationMs: 20000, at: at(102) }],
  "image-hover-transform": [
    { kind: "structure", node: "img", depth: 1, ref: "i1", at: at(103) },
    { kind: "structure", node: "img", depth: 1, ref: "i2", at: at(104) },
    { kind: "structure", node: "img", depth: 1, ref: "i3", at: at(105) },
    { kind: "motion", motionKind: "transition", props: ["transform"], at: at(103) },
  ],
  "shape-assembled-illustration": Array.from({ length: 5 }, (_, i): DesignFact[] => [
    { kind: "structure", node: "div", depth: 3, ref: `s${i}`, parentRef: "art", at: at(110 + i) },
    { kind: "radius", px: 8, at: at(110 + i) },
  ]).flat(),
  "radial-spotlight-glow": [
    { kind: "text", content: "Hero", role: "heading", level: 1, at: at(120) },
    { kind: "gradient", gradientKind: "radial", stops: [{ hex: "333333" }], at: at(122) },
  ],
};

describe("every rule fires, and stays silent on nothing", () => {
  it("covers the whole roster — a missing entry is a rule nobody proved", () => {
    expect(Object.keys(FIRES).sort()).toEqual(TELL_RULES.map((r) => r.id).sort());
  });

  for (const rule of TELL_RULES) {
    it(`${rule.id} fires on its own evidence`, () => {
      const r = lintTell(FIRES[rule.id] as DesignFact[], html);
      expect(r.findings.map((f) => f.checkId), rule.id).toContain(rule.id);
      const mine = r.findings.filter((f) => f.checkId === rule.id);
      for (const f of mine) {
        expect(f.fixHint, `${rule.id} needs a repair clause`).toBeTruthy();
        expect(f.section).toBe(rule.section);
      }
    });
  }

  it("emits nothing at all on an empty artifact", () => {
    const r = lintTell([], html);
    expect(r.findings).toEqual([]);
    expect(r.errorCount + r.warningCount + r.advisoryCount).toBe(0);
  });

  it("never lets an advisory finding change the failure count", () => {
    const r = lintTell(FIRES["cream-palette"] as DesignFact[], html);
    expect(r.advisoryCount).toBeGreaterThan(0);
    expect(r.errorCount).toBe(0);
  });

  it("orders findings deterministically", () => {
    const facts = Object.values(FIRES).flat();
    const a = JSON.stringify(lintTell(facts, html).findings);
    const b = JSON.stringify(lintTell([...facts].reverse(), html).findings);
    expect(a).toBe(b);
  });
});

describe("the false-positive floor", () => {
  it("does not call two radii in one flat file `nested-cards`", () => {
    const flat: DesignFact[] = [
      { kind: "structure", node: "div", depth: 1, ref: "a", roles: ["card"], at: at(1) },
      { kind: "structure", node: "div", depth: 1, ref: "b", roles: ["card"], at: at(2) },
      { kind: "radius", px: 16, at: at(1) },
      { kind: "radius", px: 12, at: at(2) },
    ];
    expect(lintTell(flat, html).findings.map((f) => f.checkId)).not.toContain("nested-cards");
  });

  it("does not call a three-padding component `monotonous-spacing`", () => {
    const small: DesignFact[] = [
      { kind: "structure", node: "div", depth: 0, ref: "r", at: at(1) },
      { kind: "spacing", prop: "padding-top", px: 16, at: at(1) },
      { kind: "spacing", prop: "padding-left", px: 16, at: at(1) },
      { kind: "spacing", prop: "padding-right", px: 16, at: at(1) },
    ];
    expect(lintTell(small, html).findings.map((f) => f.checkId)).not.toContain("monotonous-spacing");
  });

  it("does not call one kicker a template", () => {
    const one: DesignFact[] = [
      { kind: "text", content: "WHY IT MATTERS", role: "body", at: at(1) },
      { kind: "typography", transform: "uppercase", sizePx: 12, at: at(1) },
    ];
    expect(lintTell(one, html).findings.map((f) => f.checkId)).not.toContain("kicker-above-heading");
  });

  it("does not call a system face overused", () => {
    for (const family of ["SF Pro", "-apple-system", "Sohne", "Georgia"]) {
      const r = lintTell([{ kind: "typography", family, at: at(1) }], html);
      expect(r.findings.map((f) => f.checkId), family).not.toContain("overused-font");
    }
  });

  it("does not call a component's UI chrome scale a flat hierarchy", () => {
    // Measured on a real React app: 27 of 27 hits were 12/14/16px in component
    // files — text-xs/text-sm/text-base, which is interface text, not a broken
    // heading scale. A fragment has no display type to be flat.
    const chrome: DesignFact[] = [12, 14, 16].map((n, i) => ({ kind: "typography", sizePx: n, at: at(i + 1) }));
    expect(lintTell(chrome, html).findings.map((f) => f.checkId)).not.toContain("flat-type-hierarchy");
  });

  it("does not call a pill's padding cramped", () => {
    // `rounded-full` IS the chip case. The first threshold exempted only SMALL
    // radii and so flagged most pills in a real app.
    const pill: DesignFact[] = [
      { kind: "spacing", prop: "padding-top", px: 4, at: at(1) },
      { kind: "radius", px: 999, at: at(1) },
    ];
    expect(lintTell(pill, html).findings.map((f) => f.checkId)).not.toContain("cramped-padding");
  });

  it("still calls a real card's 4px padding cramped", () => {
    const card: DesignFact[] = [
      { kind: "spacing", prop: "padding-top", px: 4, at: at(1) },
      { kind: "radius", px: 16, at: at(1) },
    ];
    expect(lintTell(card, html).findings.map((f) => f.checkId)).toContain("cramped-padding");
  });

  it("does not call a well-ranked type scale flat", () => {
    const scale: DesignFact[] = [12, 16, 24, 40].map((n, i) => ({ kind: "typography", sizePx: n, at: at(i + 1) }));
    expect(lintTell(scale, html).findings.map((f) => f.checkId)).not.toContain("flat-type-hierarchy");
  });
});

describe("requirement view", () => {
  it("mirrors the roster exactly", () => {
    expect(TELL_REQUIREMENTS.map((r) => r.id).sort()).toEqual(TELL_RULES.map((r) => r.id).sort());
  });
});

/**
 * Guards that the first version of this suite did NOT actually guard.
 *
 * Breaking five knobs left it green: the NOT-EVALUATED bypass, side-tab's
 * one-side condition, nested-cards' parent check, the purple threshold, and the
 * deduplicator. Each was "obviously" covered by a nearby assertion that turned
 * out to test something else. These are the probes that go red.
 */
describe("guards proven by breaking them", () => {
  it("does not RUN a rule the extractor cannot feed — not merely list it", () => {
    // Hand the swiftui profile facts that WOULD trip a structure rule. Listing
    // nested-cards under notEvaluated is not enough: the rule must not fire.
    const facts: DesignFact[] = [
      { kind: "structure", node: "VStack", depth: 1, ref: "outer", roles: ["card"], at: at(1) },
      { kind: "structure", node: "VStack", depth: 2, ref: "inner", parentRef: "outer", roles: ["card"], at: at(2) },
    ];
    const r = lintTell(facts, swift);
    expect(r.findings.map((f) => f.checkId)).not.toContain("nested-cards");
    expect(r.notEvaluated.map((n) => n.id)).toContain("nested-cards");
  });

  it("does not call a four-sided border a side-tab", () => {
    const facts: DesignFact[] = [
      { kind: "border", sides: ["top", "right", "bottom", "left"], widthPx: 4, at: at(1) },
      { kind: "radius", px: 16, at: at(1) },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("side-tab");
  });

  it("does not call a thin one-sided rule a side-tab", () => {
    const facts: DesignFact[] = [
      { kind: "border", sides: ["bottom"], widthPx: 1, at: at(1) },
      { kind: "radius", px: 16, at: at(1) },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("side-tab");
  });

  it("does not call a card inside a NON-card `nested-cards`", () => {
    const facts: DesignFact[] = [
      { kind: "structure", node: "section", depth: 0, ref: "sec", at: at(1) },
      { kind: "structure", node: "div", depth: 1, ref: "card", parentRef: "sec", roles: ["card"], at: at(2) },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("nested-cards");
  });

  it("does not call navy, plum or teal the AI palette", () => {
    for (const hex of ["1e3a5f", "0b1f3a", "4a1f3d", "0f766e", "1f2937"]) {
      const r = lintTell([{ kind: "color", hex, role: "bg", at: at(1) }], html);
      expect(r.findings.map((f) => f.checkId), `#${hex}`).not.toContain("ai-color-palette");
    }
  });

  it("still calls the real purple family the AI palette", () => {
    for (const hex of ["7c3aed", "a855f7", "6366f1", "8b5cf6"]) {
      const r = lintTell([{ kind: "color", hex, role: "bg", at: at(1) }], html);
      expect(r.findings.map((f) => f.checkId), `#${hex}`).toContain("ai-color-palette");
    }
  });

  it("collapses identical findings from one declaration matching many elements", () => {
    // One stylesheet line, two elements — same line, same node locator absent.
    const dup: DesignFact[] = [
      { kind: "border", sides: ["left"], widthPx: 4, at: at(4) },
      { kind: "border", sides: ["left"], widthPx: 4, at: at(4) },
      { kind: "radius", px: 16, at: at(4) },
    ];
    const sideTabs = lintTell(dup, html).findings.filter((f) => f.checkId === "side-tab");
    expect(sideTabs).toHaveLength(1);
  });

  it("collapses the same mistake on two elements into one finding with a count", () => {
    // Two elements, one authored decision. Reporting it twice makes the reader
    // scroll; reporting it once with the count and an example is the finding
    // they can act on. Measured on a real page: 54 identical lines in one file.
    const two: DesignFact[] = [
      { kind: "border", sides: ["left"], widthPx: 4, at: { ...at(4), nodeRef: "div.a" } },
      { kind: "border", sides: ["left"], widthPx: 4, at: { ...at(4), nodeRef: "div.b" } },
      { kind: "radius", px: 16, at: at(4) },
    ];
    const sideTabs = lintTell(two, html).findings.filter((f) => f.checkId === "side-tab");
    expect(sideTabs).toHaveLength(1);
    expect(sideTabs[0]?.message).toContain("2 elements");
    expect(sideTabs[0]?.nodeRef).toBe("div.a");
  });

  it("keeps DIFFERENT mistakes apart even on the same line", () => {
    const mixed: DesignFact[] = [
      { kind: "border", sides: ["left"], widthPx: 4, at: { ...at(4), nodeRef: "div.a" } },
      { kind: "border", sides: ["right"], widthPx: 6, at: { ...at(4), nodeRef: "div.b" } },
      { kind: "radius", px: 16, at: at(4) },
    ];
    expect(lintTell(mixed, html).findings.filter((f) => f.checkId === "side-tab")).toHaveLength(2);
  });
});

describe("the purple threshold, pinned by both sides", () => {
  const isPalette = (hex: string) =>
    lintTell([{ kind: "color", hex, role: "bg", at: at(1) }], html)
      .findings.map((f) => f.checkId).includes("ai-color-palette");

  it("catches the whole violet family, indigo included", () => {
    for (const hex of ["7c3aed", "a855f7", "6366f1", "8b5cf6", "9333ea", "4f46e5"])
      expect(isPalette(hex), `#${hex} should be caught`).toBe(true);
  });

  it("leaves blue, navy, teal and plum alone", () => {
    for (const hex of ["2563eb", "3b82f6", "4169e1", "1e3a5f", "0f766e", "4a1f3d", "1f2937"])
      expect(isPalette(hex), `#${hex} should NOT be caught`).toBe(false);
  });
});

/**
 * Owner pairing. `sameOwner` is an existence check; `nearestOwner` is "THE
 * partner". Confusing them let heading-rhythm read the h2's size for the h1 the
 * moment a line window replaced line equality, so both directions are pinned.
 */
describe("owner pairing", () => {
  it("pairs a heading with ITS size, not with a neighbour's", () => {
    const facts: DesignFact[] = [
      { kind: "text", content: "H1", role: "heading", level: 1, at: at(10) },
      { kind: "typography", sizePx: 48, at: at(10) },
      { kind: "text", content: "H2", role: "heading", level: 2, at: at(11) },
      { kind: "typography", sizePx: 24, at: at(11) },
    ];
    // A correct scale: h1 48 > h2 24. Mispairing inverts it and fires the rule.
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("heading-rhythm");
  });

  it("still catches a genuinely inverted heading scale", () => {
    const facts: DesignFact[] = [
      { kind: "text", content: "H1", role: "heading", level: 1, at: at(10) },
      { kind: "typography", sizePx: 24, at: at(10) },
      { kind: "text", content: "H2", role: "heading", level: 2, at: at(20) },
      { kind: "typography", sizePx: 48, at: at(20) },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).toContain("heading-rhythm");
  });

  it("treats consecutive modifier lines as one owner when no node is named", () => {
    // The native shape: radius on one line, the edge bar on the next.
    const facts: DesignFact[] = [
      { kind: "radius", px: 16, at: { file: "v.swift", line: 24, extractor: "swiftui", confidence: "literal" } },
      { kind: "border", sides: ["left"], widthPx: 4, at: { file: "v.swift", line: 25, extractor: "swiftui", confidence: "literal" } },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).toContain("side-tab");
  });

  it("does NOT join facts from unrelated parts of a file", () => {
    const facts: DesignFact[] = [
      { kind: "radius", px: 16, at: { file: "v.swift", line: 10, extractor: "swiftui", confidence: "literal" } },
      { kind: "border", sides: ["left"], widthPx: 4, at: { file: "v.swift", line: 90, extractor: "swiftui", confidence: "literal" } },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("side-tab");
  });

  it("never joins facts from different files", () => {
    const facts: DesignFact[] = [
      { kind: "radius", px: 16, at: { file: "a.swift", line: 10, extractor: "swiftui", confidence: "literal" } },
      { kind: "border", sides: ["left"], widthPx: 4, at: { file: "b.swift", line: 10, extractor: "swiftui", confidence: "literal" } },
    ];
    expect(lintTell(facts, html).findings.map((f) => f.checkId)).not.toContain("side-tab");
  });
});
