/**
 * Human/PR renderings of a DsDiff. Pure string transforms — the binary emits the
 * text; the host posts it (e.g. `gh pr comment`). Kept separate from the impl so
 * both files stay small and the formatters are unit-testable without fs.
 */
import type { DsDiff, Severity } from "./ds-diff.js";

const MARK: Record<Severity, string> = { breaking: "⚠️ breaking", additive: "additive", patch: "patch", none: "no change" };

function countsLine(d: DsDiff): string {
  const t = d.tokens;
  const breakingTok = t.changed.filter((c) => c.severity === "breaking").length;
  return `**Tokens:** ${t.added.length} added · ${t.removed.length} removed · ${t.changed.length} changed (${breakingTok} breaking) — ` +
    `**Components:** ${d.components.added.length} added · ${d.components.removed.length} removed · ${d.components.changed.length} changed`;
}

/** Full human-readable report. */
export function formatMarkdown(d: DsDiff, baseVersion?: string): string {
  const lines: string[] = [];
  const ver = d.recommendedVersion !== undefined ? ` → recommend **${baseVersion ?? "?"} → v${d.recommendedVersion}**` : "";
  lines.push(`# Design-system diff — ${MARK[d.classification]} (${d.recommendedBump})${ver}`, "", countsLine(d), "");

  if (d.tokens.added.length + d.tokens.removed.length + d.tokens.changed.length > 0) {
    lines.push("## Tokens", "", "| path | change | from → to | ΔE | class |", "|---|---|---|---|---|");
    for (const a of d.tokens.added) lines.push(`| ${a.path} | added | — → ${a.value} | — | additive |`);
    for (const r of d.tokens.removed) lines.push(`| ${r.path} | removed | ${r.value} → — | — | **breaking** |`);
    for (const c of d.tokens.changed) {
      const cls = c.severity === "breaking" ? "**breaking**" : c.severity;
      lines.push(`| ${c.path} | changed | ${c.from} → ${c.to} | ${c.deltaE !== undefined ? c.deltaE.toFixed(3) : "—"} | ${cls} |`);
    }
    lines.push("");
  }

  if (d.components.added.length + d.components.removed.length + d.components.changed.length > 0) {
    lines.push("## Components", "");
    for (const n of d.components.added) lines.push(`- **${n}** — added (additive)`);
    for (const n of d.components.removed) lines.push(`- **${n}** — removed (**breaking**)`);
    for (const c of d.components.changed) lines.push(`- **${c.name}** (${c.severity === "breaking" ? "**breaking**" : c.severity}) — ${c.reasons.join("; ")}`);
    lines.push("");
  }

  if (d.dangling.length > 0) {
    lines.push("## ❗ Dangling references (token removed, still used)", "");
    for (const x of d.dangling) lines.push(`- ${x.component} → ${x.token}`);
    lines.push("");
  }
  return lines.join("\n") + "\n";
}

/** A GitHub-ready PR comment. Deterministic; the host posts it with `gh pr comment`. */
export function formatPrComment(d: DsDiff, baseVersion?: string): string {
  const head = d.classification === "breaking"
    ? `## ⚠️ Breaking design change${d.recommendedVersion !== undefined ? ` → recommend **${baseVersion ?? "?"} → v${d.recommendedVersion}**` : ` (recommend a **major** bump)`}`
    : d.classification === "none"
      ? "## Design system — no change"
      : `## Design change — **${d.recommendedBump}**${d.recommendedVersion !== undefined ? ` → v${d.recommendedVersion}` : ""}`;

  const lines = [head, "", countsLine(d)];
  const tokRows = [
    ...d.tokens.added.map((a) => `| ${a.path} | added | — → ${a.value} | — | additive |`),
    ...d.tokens.removed.map((r) => `| ${r.path} | removed | ${r.value} → — | — | **breaking** |`),
    ...d.tokens.changed.map((c) => `| ${c.path} | changed | ${c.from} → ${c.to} | ${c.deltaE !== undefined ? c.deltaE.toFixed(3) : "—"} | ${c.severity === "breaking" ? "**breaking**" : c.severity} |`),
  ];
  if (tokRows.length > 0) {
    lines.push("", "<details><summary>Token changes</summary>", "", "| path | change | from → to | ΔE | class |", "|---|---|---|---|---|", ...tokRows, "</details>");
  }
  const compReasons = d.components.changed.map((c) => `- ${c.name} — ${c.reasons.join(", ")}`);
  if (d.components.removed.length > 0 || compReasons.length > 0) {
    lines.push("", "**Components:** " + [...d.components.removed.map((n) => `${n} removed`), ...compReasons.map((r) => r.slice(2))].join("; "));
  }
  if (d.dangling.length > 0) {
    lines.push("", "**❗ Dangling references:** " + d.dangling.map((x) => `${x.component} → ${x.token}`).join(", "));
  }
  lines.push("", "<sub>generated by `ui ds diff`</sub>");
  return lines.join("\n") + "\n";
}
