/**
 * User-evidence model (DESIGN-OS T6) — the pure shape + the anti-fabrication gate.
 * A design decision should be traceable to real user evidence, not assertion. The
 * load-bearing rule: a `quote` finding must be a VERBATIM substring of its source
 * text (whitespace-normalised, never lower-cased), so the binary cannot invent a
 * user's words. `metric` findings need a source ref; `observation` findings are
 * accepted but flagged `unsupported` (the same honesty spirit as T0's assumptions).
 * Pure — no IO. The store module reads/writes files; here we only validate & match.
 */

export type EvidenceKind = "quote" | "metric" | "observation";
export type Support = "quoted" | "metric" | "unsupported";

export interface EvidenceSource {
  /** Basename of the source file kept under the store's research-sources/ dir. */
  ref: string;
  /** interview | survey | analytics | support | review | usability-test | field | other. */
  medium?: string;
  /** Where in the source (line 42, 0:14:20, row 88) — provenance for a human, not verified. */
  locator?: string;
}
export interface EvidenceMetric {
  value: string;
  unit?: string;
  /** Sample size, when known. */
  n?: number;
}
export interface EvidenceRecord {
  id: string;
  kind: EvidenceKind;
  /** The synthesised insight — what we learned. */
  finding: string;
  /** Verbatim source text; required for kind=quote. */
  quote?: string;
  metric?: EvidenceMetric;
  source?: EvidenceSource;
  tags?: string[];
  /** Optional event timestamp (ms). Never generated by the binary. */
  t?: number;
}

export class EvidenceError extends Error {
  constructor(public code: string, message: string) {
    super(message);
    this.name = "EvidenceError";
  }
}

/** Shortest quote we will verify — below this, a substring match is meaningless ("the"). */
export const MIN_QUOTE_CHARS = 8;

export function supportOf(r: EvidenceRecord): Support {
  return r.kind === "quote" ? "quoted" : r.kind === "metric" ? "metric" : "unsupported";
}

/** Collapse whitespace runs to a single space and trim; preserves case (verbatim). */
export function normalizeText(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

/** Does `quote` appear verbatim (whitespace-normalised) inside `sourceText`? */
export function quoteMatches(quote: string, sourceText: string): boolean {
  const q = normalizeText(quote);
  if (q.length < MIN_QUOTE_CHARS) return false;
  return normalizeText(sourceText).includes(q);
}

/** Enforce the quote-when-claimed policy for a new record. Throws EvidenceError. */
export function validateForAdd(
  kind: EvidenceKind,
  fields: { finding?: string; quote?: string; source?: EvidenceSource; metric?: EvidenceMetric },
): void {
  if (fields.finding === undefined || fields.finding.trim() === "") {
    throw new EvidenceError("BAD_ARG", "a finding is required (what did we learn?)");
  }
  if (kind === "quote") {
    if (fields.quote === undefined || fields.quote.trim() === "") throw new EvidenceError("BAD_ARG", "kind=quote requires --quote");
    if (normalizeText(fields.quote).length < MIN_QUOTE_CHARS) throw new EvidenceError("QUOTE_TOO_SHORT", `quote must be at least ${MIN_QUOTE_CHARS} characters to be verifiable`);
    if (fields.source === undefined) throw new EvidenceError("BAD_ARG", "kind=quote requires a --source to verify against");
  } else if (kind === "metric") {
    if (fields.metric === undefined) throw new EvidenceError("BAD_ARG", "kind=metric requires --metric \"<value> [unit]\"");
    if (fields.source === undefined) throw new EvidenceError("BAD_ARG", "kind=metric requires a --source reference");
  }
  // observation: nothing else required; it will read as `unsupported`.
}

/** Parse & validate one stored record (a JSONL line already JSON-parsed). */
export function parseEvidence(obj: unknown, ctx: string): EvidenceRecord {
  if (typeof obj !== "object" || obj === null) throw new EvidenceError("BAD_EVIDENCE", `${ctx}: not an object`);
  const o = obj as Record<string, unknown>;
  const id = o["id"];
  const kind = o["kind"];
  const finding = o["finding"];
  if (typeof id !== "string" || id === "") throw new EvidenceError("BAD_EVIDENCE", `${ctx}: missing 'id'`);
  if (kind !== "quote" && kind !== "metric" && kind !== "observation") throw new EvidenceError("BAD_EVIDENCE", `${ctx}: bad 'kind' (${String(kind)})`);
  if (typeof finding !== "string" || finding === "") throw new EvidenceError("BAD_EVIDENCE", `${ctx}: missing 'finding'`);
  const rec: EvidenceRecord = { id, kind, finding };
  if (typeof o["quote"] === "string") rec.quote = o["quote"];
  if (typeof o["t"] === "number") rec.t = o["t"];
  if (Array.isArray(o["tags"])) rec.tags = o["tags"].filter((x): x is string => typeof x === "string");
  const src = o["source"];
  if (typeof src === "object" && src !== null) {
    const s = src as Record<string, unknown>;
    if (typeof s["ref"] === "string") {
      rec.source = { ref: s["ref"] };
      if (typeof s["medium"] === "string") rec.source.medium = s["medium"];
      if (typeof s["locator"] === "string") rec.source.locator = s["locator"];
    }
  }
  const met = o["metric"];
  if (typeof met === "object" && met !== null) {
    const m = met as Record<string, unknown>;
    if (typeof m["value"] === "string") {
      rec.metric = { value: m["value"] };
      if (typeof m["unit"] === "string") rec.metric.unit = m["unit"];
      if (typeof m["n"] === "number") rec.metric.n = m["n"];
    }
  }
  return rec;
}

/** Serialise a record to a canonical one-line JSON (stable key order). */
export function serializeEvidence(r: EvidenceRecord): string {
  const ordered: Record<string, unknown> = { id: r.id, kind: r.kind, finding: r.finding };
  if (r.quote !== undefined) ordered["quote"] = r.quote;
  if (r.metric !== undefined) ordered["metric"] = r.metric;
  if (r.source !== undefined) ordered["source"] = r.source;
  if (r.tags !== undefined) ordered["tags"] = r.tags;
  if (r.t !== undefined) ordered["t"] = r.t;
  return JSON.stringify(ordered);
}

/** Next sequential id (ev1, ev2, …) given existing records. */
export function nextEvidenceId(existing: readonly EvidenceRecord[]): string {
  let max = 0;
  for (const r of existing) {
    const m = /^ev(\d+)$/.exec(r.id);
    if (m) max = Math.max(max, Number(m[1]));
  }
  return `ev${max + 1}`;
}
