/**
 * Resolve WHAT a Figma comment is pointing at (spec: figma comment triage).
 *
 * Figma hands us a frame id and a point. It never names the element. Naming it is a
 * containment walk we do ourselves, offline, over a captured `/nodes` payload — pure,
 * deterministic, network-free (Art. I).
 *
 * The walk deliberately does NOT return "the deepest containing node". In real
 * auto-layout the deepest hit is routinely a full-bleed background rect, a 4px spacer,
 * or a bare Vector inside an icon; "anchored to Rectangle 47" is worse than no answer,
 * because a confidently wrong anchor poisons the task it becomes. We emit the ANCESTOR
 * CHAIN and label the leaf's trustworthiness instead.
 */

import type {
  AnchorConfidence,
  CommentAnchor,
  FigmaNode,
  ResolvedAnchor,
} from "./figma-comment-types.js";

export type { AnchorConfidence, FigmaNode, ResolvedAnchor } from "./figma-comment-types.js";

interface Box {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Generated names Figma assigns when nobody named the layer. They identify nothing. */
const AUTOGENERATED_NAME =
  /^(Rectangle|Ellipse|Vector|Line|Group|Frame|Union|Subtract|Intersect|Exclude|Polygon|Star|Arrow|Slice|Component)(\s+\d+)?$/i;

/** Below this, a node is decoration or a spacer rather than a thing to talk about. */
const MIN_MEANINGFUL_PX = 8;

/** Types that reliably name a real UI thing when the layer itself is named. */
const STRONG_TYPES = new Set(["TEXT", "INSTANCE", "COMPONENT", "COMPONENT_SET"]);

function box(node: FigmaNode): Box | null {
  const b = node.absoluteBoundingBox;
  if (!b || typeof b !== "object") return null;
  const { x, y, width, height } = b;
  if (![x, y, width, height].every((v) => typeof v === "number" && Number.isFinite(v))) return null;
  return { x, y, width, height };
}

function contains(b: Box, px: number, py: number): boolean {
  return px >= b.x && px <= b.x + b.width && py >= b.y && py <= b.y + b.height;
}

/** Longest text excerpt worth putting in an anchor chain before it stops being a label. */
const MAX_TEXT_LABEL = 40;

/**
 * What to call this node in a chain a human reads.
 *
 * For TEXT nodes prefer `characters` over `name`. Measured on a real file: a text node
 * inside an instance had name "No transformation plan — the system is maintained as is."
 * while `characters` — the actual override on screen — read "Target date 20/12/2026 · …".
 * Reporting the name there points the reader at words that are not on the canvas, which is
 * a wrong answer wearing the costume of a right one.
 */
function nameOf(node: FigmaNode): string {
  if (node.type === "TEXT" && typeof node.characters === "string") {
    const text = node.characters.trim().replace(/\s+/g, " ");
    if (text.length > 0) {
      return text.length > MAX_TEXT_LABEL ? `${text.slice(0, MAX_TEXT_LABEL - 1)}…` : text;
    }
  }
  return typeof node.name === "string" ? node.name : "";
}

/** A name worth showing a human: present, not Figma's autogenerated filler. */
function isMeaningful(node: FigmaNode): boolean {
  const name = nameOf(node);
  if (!name || AUTOGENERATED_NAME.test(name.trim())) return false;
  const b = box(node);
  if (b && (b.width < MIN_MEANINGFUL_PX || b.height < MIN_MEANINGFUL_PX)) return false;
  return true;
}

/**
 * Map every top-level frame id to its page name.
 *
 * Only `GET /v1/files/:key?depth=2` carries this: `/nodes` returns a node's SUBTREE,
 * never its ancestry, so it cannot tell you which page a frame sits on. Two pages
 * routinely own a frame called "Checkout" — that is why grouping keys on node_id and
 * the page name is display only.
 */
export function buildPageIndex(fileTree: unknown): Map<string, string> {
  const index = new Map<string, string>();
  const doc = (fileTree as { document?: FigmaNode } | null)?.document;
  const pages = Array.isArray(doc?.children) ? doc.children : [];
  for (const page of pages) {
    const pageName = nameOf(page);
    for (const child of Array.isArray(page.children) ? page.children : []) {
      const id = typeof child.id === "string" ? child.id : "";
      if (id) index.set(id, pageName);
    }
  }
  return index;
}

/**
 * Index the `nodes: { "<id>": { document: Node } }` map from GET /nodes — EVERY node in
 * each returned subtree, not just the requested roots.
 *
 * Indexing only the roots looks sufficient and is not: a comment routinely anchors to a
 * frame nested inside the node you asked for (fetch one section, get comments on the
 * frames inside it). Those frames would then miss the index and every one of them would
 * be reported "orphaned" — a wrong answer, not an error.
 */
export function buildNodeIndex(nodesPayload: unknown): Map<string, FigmaNode> {
  const index = new Map<string, FigmaNode>();
  const nodes = (nodesPayload as { nodes?: Record<string, { document?: FigmaNode }> } | null)?.nodes;
  if (!nodes || typeof nodes !== "object") return index;
  for (const [id, entry] of Object.entries(nodes)) {
    const doc = entry?.document;
    if (doc && typeof doc === "object") {
      index.set(id, doc); // keyed by the REQUESTED id, which may differ in punctuation
      indexSubtree(doc, index);
    }
  }
  return index;
}

/** Walk a node and register every descendant by its own id. Cycle-safe by construction. */
function indexSubtree(node: FigmaNode, index: Map<string, FigmaNode>): void {
  const id = typeof node.id === "string" ? node.id : "";
  if (id && !index.has(id)) index.set(id, node);
  for (const child of Array.isArray(node.children) ? node.children : []) {
    indexSubtree(child, index);
  }
}

/**
 * Collect `rootId` and every descendant id beneath it — the set used to scope triage to
 * one section or page. Returns an empty set when the root is not in the payload, which
 * callers must treat as "cannot scope" rather than "nothing matched".
 */
export function collectDescendantIds(rootId: string, index: Map<string, FigmaNode>): Set<string> {
  const root = index.get(rootId);
  const ids = new Set<string>();
  if (!root) return ids;
  const walk = (node: FigmaNode): void => {
    const id = typeof node.id === "string" ? node.id : "";
    if (id) ids.add(id);
    for (const child of Array.isArray(node.children) ? node.children : []) walk(child);
  };
  walk(root);
  ids.add(rootId);
  return ids;
}

/**
 * Descend from the frame collecting every node that contains the point, deepest last.
 * Invisible nodes are skipped entirely — a hidden layer is not what the comment means.
 */
function descend(frame: FigmaNode, px: number, py: number): FigmaNode[] {
  const path: FigmaNode[] = [];
  let current: FigmaNode | undefined = frame;

  while (current) {
    path.push(current);
    let next: FigmaNode | undefined;
    for (const child of Array.isArray(current.children) ? current.children : []) {
      if (child.visible === false) continue;
      const b = box(child);
      // Last match wins. Figma sorts children back-to-front — "the first child in the
      // array is the bottommost layer, the last child is the topmost" (Plugin API,
      // FrameNode.children). The REST schema does not restate it, but the document order
      // is the same one. This also settles ties on a shared edge, where `contains`'
      // inclusive bounds match both siblings: the topmost one is what the user clicked.
      if (b && contains(b, px, py)) next = child;
    }
    current = next;
  }
  return path;
}

/**
 * Resolve one comment anchor against captured payloads.
 *
 * `nodeIndex` and `pageIndex` are both optional: with neither, a frame-anchored comment
 * still resolves to its frame id, and the command degrades to grouping rather than
 * failing. Partial evidence beats a hard error the user cannot act on at 8am.
 */
export function resolveAnchor(
  anchor: CommentAnchor,
  nodeIndex: Map<string, FigmaNode>,
  pageIndex: Map<string, string>,
): ResolvedAnchor {
  if (anchor.kind === "canvas") {
    return {
      frameId: null,
      frameName: null,
      pageName: null,
      chain: [],
      element: null,
      confidence: "unanchored",
      pin: null,
    };
  }

  const frameId = anchor.nodeId;
  const pageName = pageIndex.get(frameId) ?? null;
  const frame = nodeIndex.get(frameId);
  const pin = { x: anchor.offset.x, y: anchor.offset.y };

  if (!frame) {
    // Absent from the /nodes map = deleted since the comment was written. Never throw.
    const known = nodeIndex.size > 0;
    return {
      frameId,
      frameName: null,
      pageName,
      chain: [],
      element: null,
      confidence: known ? "orphaned" : "frame",
      pin,
    };
  }

  const frameBox = box(frame);
  const frameName = nameOf(frame) || null;
  if (!frameBox) {
    return { frameId, frameName, pageName, chain: [], element: null, confidence: "frame", pin };
  }

  // node_offset is frame-LOCAL; absoluteBoundingBox is canvas-ABSOLUTE. Converting between
  // them is the whole ballgame — skip it and every element name comes out confidently wrong.
  const px = frameBox.x + anchor.offset.x;
  const py = frameBox.y + anchor.offset.y;

  const path = descend(frame, px, py);
  const meaningful = path.filter(isMeaningful);
  const chain = meaningful.map(nameOf);
  const leaf = meaningful.length > 0 ? meaningful[meaningful.length - 1] : undefined;
  const deepest = path.length > 0 ? path[path.length - 1] : undefined;

  // "element" only when the innermost SURVIVING node is also the node actually hit, or is
  // a strongly-typed named node. If the real hit was junk we filtered, say "region" —
  // the chain is still true, the leaf claim would not be.
  const leafIsHit = leaf !== undefined && deepest !== undefined && leaf === deepest;
  const leafIsStrong = leaf !== undefined && STRONG_TYPES.has(String(leaf.type ?? ""));
  const confidence: AnchorConfidence =
    leaf === undefined ? "frame" : leafIsHit || leafIsStrong ? "element" : "region";

  return {
    frameId,
    frameName,
    pageName,
    chain,
    element: leaf ? nameOf(leaf) : null,
    confidence,
    pin,
  };
}
